-- Catálogos canônicos do módulo Segurança do Trabalho (GERADO — não edite manualmente)
-- Fonte: gov.br eSocial S-1.3 Tabela 24 + lista de NRs · scripts/seguranca/import-catalog.mjs

INSERT INTO seg_esocial_tables (code, name, layout_version) VALUES
  ('24', 'Agentes Nocivos - Aposentadoria Especial', 'S-1.3')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, layout_version = EXCLUDED.layout_version;

INSERT INTO seg_esocial_agents (code, table_code, grp, subgroup, agent, active) VALUES
  ('01.01.001', '24', 'QUÍMICOS', 'ARSÊNIO E SEUS COMPOSTOS', 'Arsênio e seus compostos', true),
  ('01.02.001', '24', 'QUÍMICOS', 'ASBESTOS', 'Asbestos (ou amianto)', true),
  ('01.03.001', '24', 'QUÍMICOS', 'BENZENO E SEUS COMPOSTOS TÓXICOS', 'Benzeno e seus compostos tóxicos (exceto os abaixo especificados, que constam expressamente no Anexo IV do Decreto 3.048/1999)', true),
  ('01.03.002', '24', 'QUÍMICOS', 'BENZENO E SEUS COMPOSTOS TÓXICOS', 'Estireno (vinilbenzeno)', true),
  ('01.04.001', '24', 'QUÍMICOS', 'BERÍLIO E SEUS COMPOSTOS TÓXICOS', 'Berílio e seus compostos tóxicos', true),
  ('01.05.001', '24', 'QUÍMICOS', 'BROMO E SEUS COMPOSTOS TÓXICOS', 'Bromo e seus compostos tóxicos', true),
  ('01.06.001', '24', 'QUÍMICOS', 'CÁDMIO E SEUS COMPOSTOS TÓXICOS', 'Cádmio e seus compostos tóxicos', true),
  ('01.07.001', '24', 'QUÍMICOS', 'CARVÃO MINERAL E SEUS DERIVADOS', 'Carvão mineral e seus derivados', true),
  ('01.08.001', '24', 'QUÍMICOS', 'CHUMBO E SEUS COMPOSTOS TÓXICOS', 'Chumbo e seus compostos tóxicos', true),
  ('01.09.001', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Cloro e seus compostos tóxicos (exceto os abaixo especificados, que constam expressamente no Anexo IV do Decreto 3.048/1999)', true),
  ('01.09.002', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Metileno-ortocloroanilina, MOCA® (4,4''-metileno-bis-(2-cloroanilina), MBOCA®)', true),
  ('01.09.003', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Bis (cloro metil) éter, clorometileter, (éter bis (clorometílico) ou éter metílico de clorometila), bisclorometil', true),
  ('01.09.004', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Biscloroetileter (éter dicloroetílico)', true),
  ('01.09.005', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Clorambucil (cloroambucil)', true),
  ('01.09.006', '24', 'QUÍMICOS', 'CLORO E SEUS COMPOSTOS TÓXICOS', 'Cloropreno', true),
  ('01.10.001', '24', 'QUÍMICOS', 'CROMO E SEUS COMPOSTOS TÓXICOS', 'Cromo e seus compostos tóxicos', true),
  ('01.11.001', '24', 'QUÍMICOS', 'DISSULFETO DE CARBONO', 'Dissulfeto de carbono', true),
  ('01.12.001', '24', 'QUÍMICOS', 'FÓSFORO E SEUS COMPOSTOS TÓXICOS', 'Fósforo e seus compostos tóxicos', true),
  ('01.13.001', '24', 'QUÍMICOS', 'IODO', 'Iodo', true),
  ('01.14.001', '24', 'QUÍMICOS', 'MANGANÊS E SEUS COMPOSTOS', 'Manganês e seus compostos', true),
  ('01.15.001', '24', 'QUÍMICOS', 'MERCÚRIO E SEUS COMPOSTOS', 'Mercúrio e seus compostos', true),
  ('01.16.001', '24', 'QUÍMICOS', 'NÍQUEL E SEUS COMPOSTOS TÓXICOS', 'Níquel e seus compostos tóxicos PETRÓLEO, XISTO BETUMINOSO, GÁS NATURAL E SEUS DERIVADOS', true),
  ('01.17.001', '24', 'QUÍMICOS', 'NÍQUEL E SEUS COMPOSTOS TÓXICOS', 'Petróleo, xisto betuminoso, gás natural e seus derivados', true),
  ('01.18.001', '24', 'QUÍMICOS', 'SÍLICA LIVRE', 'Sílica livre', true),
  ('01.19.001', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Butadieno-estireno', true),
  ('01.19.002', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Acrilonitrila', true),
  ('01.19.003', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', '1-3-butadieno', true),
  ('01.19.004', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Mercaptanos (tióis)', true),
  ('01.19.005', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'n-hexano', true),
  ('01.19.006', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Diisocianato de tolueno (TDI)', true),
  ('01.19.007', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Aminas aromáticas', true),
  ('01.19.008', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Aminobifenila (4-aminodifenil)', true),
  ('01.19.009', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Auramina', true),
  ('01.19.010', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Azatioprina', true),
  ('01.19.011', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', '1-4-butanodiol', true),
  ('01.19.012', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Dimetanosulfonato (MIRELAN)', true),
  ('01.19.013', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Ciclofosfamida', true),
  ('01.19.014', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Dietiletil-bestrol', true),
  ('01.19.015', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Acronitrila', true),
  ('01.19.016', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Nitronaftilamina', true),
  ('01.19.017', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', '4-dimetil-aminoazobenzeno', true),
  ('01.19.018', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Benzopireno', true),
  ('01.19.019', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Beta-pbiscloromeropiolactona (beta-propiolactona)', true),
  ('01.19.021', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Dianizidina', true),
  ('01.19.022', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Dietilsulfato', true),
  ('01.19.023', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Dimetilsulfato', true),
  ('01.19.024', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Etilenoamina', true),
  ('01.19.025', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Etilenotiureia', true),
  ('01.19.026', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Fenacetina', true),
  ('01.19.027', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Iodeto de metila', true),
  ('01.19.028', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Etilnitrosureia', true),
  ('01.19.029', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Nitrosamina', true),
  ('01.19.030', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Ortotoluidina', true),
  ('01.19.031', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Oximetalona (oxime-talona)', true),
  ('01.19.032', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Procarbazina', true),
  ('01.19.033', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Propanosultona', true),
  ('01.19.034', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Óxido de etileno', true),
  ('01.19.035', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Estilbenzeno (etilbenzeno)', true),
  ('01.19.036', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Creosoto', true),
  ('01.19.038', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Benzidina', true),
  ('01.19.039', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', 'Betanaftilamina', true),
  ('01.19.040', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', '1-cloro-2,4-nitrodifenil', true),
  ('01.19.041', '24', 'QUÍMICOS', 'OUTRAS SUBSTÂNCIAS QUÍMICAS', '3-poxipro-pano', true),
  ('02.01.001', '24', 'FÍSICOS', 'RUÍDO', 'Ruído', true),
  ('02.01.002', '24', 'FÍSICOS', 'VIBRAÇÕES', 'Vibrações localizadas (mão-braço)', true),
  ('02.01.003', '24', 'FÍSICOS', 'VIBRAÇÕES', 'Vibração de corpo inteiro (aceleração resultante de exposição normalizada - aren)', true),
  ('02.01.004', '24', 'FÍSICOS', 'VIBRAÇÕES', 'Vibração de corpo inteiro (Valor da Dose de Vibração Resultante - VDVR)', true),
  ('02.01.005', '24', 'FÍSICOS', 'VIBRAÇÕES', 'Trabalhos com perfuratrizes e marteletes pneumáticos', true),
  ('02.01.006', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Radiações ionizantes', true),
  ('02.01.007', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Extração e beneficiamento de minerais radioativos', true),
  ('02.01.008', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Atividades em minerações com exposição ao radônio', true),
  ('02.01.009', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Realização de manutenção e supervisão em unidades de extração, tratamento e beneficiamento de minerais radioativos com exposição às radiações ionizantes', true),
  ('02.01.010', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Operações com reatores nucleares ou com fontes radioativas', true),
  ('02.01.011', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Trabalhos realizados com exposição aos raios Alfa, Beta, Gama e X, aos nêutrons e às substâncias radioativas para fins industriais, terapêuticos e diagnósticos', true),
  ('02.01.012', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Fabricação e manipulação de produtos radioativos', true),
  ('02.01.013', '24', 'FÍSICOS', 'RADIAÇÕES IONIZANTES', 'Pesquisas e estudos com radiações ionizantes em laboratórios', true),
  ('02.01.014', '24', 'FÍSICOS', 'TEMPERATURAS ANORMAIS', 'Trabalhos com exposição ao calor nos termos da NR-15, da Portaria 3.214/1978', true),
  ('02.01.015', '24', 'FÍSICOS', 'PRESSÃO ATMOSFÉRICA ANORMAL', 'Pressão atmosférica anormal', true),
  ('02.01.016', '24', 'FÍSICOS', 'PRESSÃO ATMOSFÉRICA ANORMAL', 'Trabalhos em caixões ou câmaras hiperbáricas', true),
  ('02.01.017', '24', 'FÍSICOS', 'PRESSÃO ATMOSFÉRICA ANORMAL', 'Trabalhos em tubulões ou túneis sob ar comprimido', true),
  ('02.01.018', '24', 'FÍSICOS', 'PRESSÃO ATMOSFÉRICA ANORMAL', 'Operações de mergulho com o uso de escafandros ou outros equipamentos', true),
  ('03.01.001', '24', 'BIOLÓGICOS', '', 'Trabalhos em estabelecimentos de saúde com contato com pacientes portadores de doenças infectocontagiosas ou com manuseio de materiais contaminados', true),
  ('03.01.002', '24', 'BIOLÓGICOS', '', 'Trabalhos com animais infectados para tratamento ou para o preparo de soro, vacinas e outros produtos', true),
  ('03.01.003', '24', 'BIOLÓGICOS', '', 'Trabalhos em laboratórios de autópsia, de anatomia e anátomo-histologia', true),
  ('03.01.004', '24', 'BIOLÓGICOS', '', 'Trabalho de exumação de corpos e manipulação de resíduos de animais deteriorados', true),
  ('03.01.005', '24', 'BIOLÓGICOS', '', 'Trabalhos em galerias, fossas e tranques de esgoto', true),
  ('03.01.006', '24', 'BIOLÓGICOS', '', 'Esvaziamento de biodigestores', true),
  ('03.01.007', '24', 'BIOLÓGICOS', '', 'Coleta e industrialização do lixo ASSOCIAÇÃO DE AGENTES NOCIVOS FÍSICOS, QUÍMICOS E BIOLÓGICOS', true),
  ('04.01.001', '24', 'BIOLÓGICOS', '', 'Mineração subterrânea cujas atividades sejam exercidas afastadas das frentes de produção', true),
  ('04.01.002', '24', 'BIOLÓGICOS', '', 'Trabalhos em atividades permanentes no subsolo de minerações subterrâneas em frente de produção', true),
  ('05.01.001', '24', 'OUTROS', '', 'Agentes nocivos não constantes no Anexo IV do Decreto 3.048/1999 e incluídos por força de decisão judicial ou administrativa', true),
  ('09.01.001', '24', 'AUSÊNCIA', '', 'Ausência de agente nocivo ou de atividades previstas no Anexo IV do Decreto 3.048/1999', true)
ON CONFLICT (code) DO UPDATE SET grp = EXCLUDED.grp, subgroup = EXCLUDED.subgroup, agent = EXCLUDED.agent, active = EXCLUDED.active;

INSERT INTO seg_nrs (code, title, summary, url, active) VALUES
  ('NR-01', 'DISPOSIÇÕES GERAIS E GERENCIAMENTO DE RISCOS OCUPACIONAIS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/nr-1', true),
  ('NR-02', 'INSPEÇÃO PRÉVIA', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-2-nr-2', false),
  ('NR-03', 'EMBARGO E INTERDIÇÃO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-3-nr-3', true),
  ('NR-04', 'SERVIÇOS ESPECIALIZADOS EM SEGURANÇA E EM MEDICINA DO TRABALHO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-4-nr-4', true),
  ('NR-05', 'COMISSÃO INTERNA DE PREVENÇÃO DE ACIDENTES', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-5-nr-5', true),
  ('NR-06', 'EQUIPAMENTO DE PROTEÇÃO INDIVIDUAL - EPI', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-6-nr-6', true),
  ('NR-07', 'PROGRAMA DE CONTROLE MÉDICO DE SAÚDE OCUPACIONAL', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-7-nr-7', true),
  ('NR-08', 'EDIFICAÇÕES', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-8-nr-8', true),
  ('NR-10', 'SEGURANÇA EM INSTALAÇÕES E SERVIÇOS EM ELETRICIDADE', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-10-nr-10', true),
  ('NR-11', 'TRANSPORTE, MOVIMENTAÇÃO, ARMAZENAGEM E MANUSEIO DE MATERIAIS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-11-nr-11', true),
  ('NR-12', 'SEGURANÇA NO TRABALHO EM MÁQUINAS E EQUIPAMENTOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-12-nr-12', true),
  ('NR-13', 'CALDEIRAS, VASOS DE PRESSÃO E TUBULAÇÕES E TANQUES METÁLICOS DE ARMAZENAMENTO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-13-nr-13', true),
  ('NR-14', 'FORNOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-14-nr-14', true),
  ('NR-15', 'ATIVIDADES E OPERAÇÕES INSALUBRES', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-15-nr-15', true),
  ('NR-16', 'ATIVIDADES E OPERAÇÕES PERIGOSAS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-16-nr-16', true),
  ('NR-17', 'ERGONOMIA', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-17-nr-17', true),
  ('NR-19', 'EXPLOSIVOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-19-nr-19', true),
  ('NR-20', 'SEGURANÇA E SAÚDE NO TRABALHO COM INFLAMÁVEIS E COMBUSTÍVEIS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-20-nr-20', true),
  ('NR-21', 'TRABALHOS A CÉU ABERTO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-21-nr-21', true),
  ('NR-22', 'SEGURANÇA E SAÚDE OCUPACIONAL NA MINERAÇÃO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-22-nr-22', true),
  ('NR-23', 'PROTEÇÃO CONTRA INCÊNDIOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-23-nr-23', true),
  ('NR-24', 'CONDIÇÕES SANITÁRIAS E DE CONFORTO NOS LOCAIS DE TRABALHO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-24-nr-24', true),
  ('NR-25', 'RESÍDUOS INDUSTRIAIS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-25-nr-25', true),
  ('NR-26', 'SINALIZAÇÃO DE SEGURANÇA', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-26-nr-26', true),
  ('NR-27', 'REGISTRO PROFISSIONAL DO TÉCNICO DE SEGURANÇA DO TRABALHO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-27-nr-27', false),
  ('NR-28', 'FISCALIZAÇÃO E PENALIDADES', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-28-nr-28', true),
  ('NR-29', 'NORMA REGULAMENTADORA DE SEGURANÇA E SAÚDE NO TRABALHO PORTUÁRIO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-29-nr-29', true),
  ('NR-30', 'SEGURANÇA E SAÚDE NO TRABALHO AQUAVIÁRIO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-30-nr-30', true),
  ('NR-31', 'SEGURANÇA E SAÚDE NO TRABALHO NA AGRICULTURA, PECUÁRIA SILVICULTURA, EXPLORAÇÃO FLORESTAL E AQUICULTURA', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-31-nr-31', true),
  ('NR-32', 'SEGURANÇA E SAÚDE NO TRABALHO EM SERVIÇOS DE SAÚDE', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-32-nr-32', true),
  ('NR-33', 'SEGURANÇA E SAÚDE NOS TRABALHOS EM ESPAÇOS CONFINADOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-33-nr-33', true),
  ('NR-34', 'CONDIÇÕES E MEIO AMBIENTE DE TRABALHO NA INDÚSTRIA DA CONSTRUÇÃO, REPARAÇÃO E DESMONTE NAVAL', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-34-nr-34', true),
  ('NR-35', 'TRABALHO EM ALTURA', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-35-nr-35', true),
  ('NR-36', 'SEGURANÇA E SAÚDE NO TRABALHO EM EMPRESAS DE ABATE E PROCESSAMENTO DE CARNES E DERIVADOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-36-nr-36', true),
  ('NR-37', 'SEGURANÇA E SAÚDE EM PLATAFORMAS DE PETRÓLEO', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/inspecao-do-trabalho/seguranca-e-saude-no-trabalho/ctpp-nrs/norma-regulamentadora-no-37-nr-37', true),
  ('NR-38', 'SEGURANÇA E SAÚDE NO TRABALHO NAS ATIVIDADES DE LIMPEZA URBANA E MANEJO DE RESÍDUOS SÓLIDOS', NULL, 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/norma-regulamentadora-no-38-nr-38', true)
ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, url = EXCLUDED.url, active = EXCLUDED.active;
